site_name: 深圳生活小结
theme:
  name: material
  features:
    - navigation.indexes

# 搜索功能目前不支持中文，隐藏暂时搜索框。
plugins: []

nav:
  - 概述: index.md
  - '下沙租房.md'
  - '广州到深圳的交通工具.md'
  - '地铁.md'
  - '医院.md'
  - '医保.md'
  - '宽带.md'
  - '游泳馆.md'
  - '资讯获取.md'

